### PR TITLE
Fixed"Bug"UDP Frame 1E

### PR DESCRIPTION
**Pull request by john102594**
Add compatibility with plc fx3g,fx3u and fx3u-enet with UDP protocol in Frame 1E
image

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Hi thank you very much for your contribution.

A few of questions before I commit ...

1. Where in the first commit ([5c139af](https://github.com/Steve-Mcl/node-red-contrib-mcprotocol/pull/14/commits/5c139afecced6a2247076ca4698563fae572625f)) are the bits that have changed? 
   * With there being so much linting in the same commit, it is hard to see what has changed :-/
   * I don't mind the linting but would have much preferred the linting as a separate PR (or at least a separate commit in the PR)
2. Is the 2nd commit ([3b8b66d](https://github.com/Steve-Mcl/node-red-contrib-mcprotocol/pull/14/commits/3b8b66dccbe203a6843ba6feaae8492a6ae93a04)) identical to the PR #11 or are there additional changes in this commit?
3. Are you using code in production? 
   * what is your confidence
   * unfortunately I no longer have access to Mitsubishi PLCs (only a hand written emulator)

**Comment by Steve-Mcl** [comment]
Sorry, I see where you have added 1 part 
image

Question: Shouldn't there be a separate field for PC Port? What if the user sets a different dest port?
image

**Comment by john102594** [comment]
Hi Steve, yes the ideal is to have a field for configuration of PC port in
the node of connection. Currently i used this library on production with
plc f3ge, fx5u and Q cpu. Sorry for my English.

**Comment by Huynhbaoky** [comment]
Hi Steve, John.
As I follow on you shared. But still error timeout. Please verify and support solve this issue.
image

Thank you

**Comment by john102594** [comment]
> Hi Steve, John. As I follow on you shared. But still error timeout. Please verify and support solve this issue. image
> 
> Thank you

**Comment by john102594** [comment]
Hi Huynhbaoky, in the destiaton IP field you must put the ip of your pc, in node-red you must put the ip of your PLC fx3g
Below is an example configuration:
image

image


Best Regards

**Comment by Huynhbaoky** [comment]
Hi Steve,John,
Based on your advice, I have already solved this problem.But I have an
idea. You can add this code in node-red-contrib-mcprotocol and upgrade
version 1.2.1 to 1.2.2
Thank you

Vào Th 4, 22 thg 3, 2023 vào lúc 04:10 john102594 <
***@***.***> đã viết:

**Pull request closed without merging**
